### ISSUE TITLE
Project status in Julia v0.6?

### ISSUE THREAD

**Issue by juliohm** [JuliaCollections/Iterators.jl#103]
What is the project status in Julia v0.6? It seems that an `Iterators` module is part of `Base` now?

**Comment by iamed2** [comment]
Despite providing similar functionality for some functions, the Iterators module in Base and the Iterators package are barely related. Base.Iterators contains only the iterators needed to implement Base functionality.

**Comment by juliohm** [comment]
Thank you @iamed2, what is the plan to avoid the binding warning then?

```julia
using Iterators
WARNING: imported binding for Iterators overwritten in module Main
```

**Comment by iamed2** [comment]
That error does not occur when you have not imported `Base.Iterators`. The plan is to eventually reexport all `Base.Iterators` functions from this package, but there are currently API inconsistencies which will need to be resolved.

**Comment by juliohm** [comment]
The issue is invalid with the migration to IterTools.jl
