### ISSUE TITLE
Move this package to a different organization?

### ISSUE THREAD

**Issue by tkelman** [JuliaCollections/Iterators.jl#96]
Mostly so it doesn't share a Travis queue with Base. It would make sense to put this, DataStructures, FunctionalCollections, and SortingAlgorithms in the same place I think. I've created a JuliaExtras (was briefly called JuliaUtils and before that JuliaAlgorithms, changed based on suggestion of @kmsquire) placeholder organization that would work, unless anyone has better naming suggestions. Happy to invite any contributors there.

**Comment by iamed2** [comment]
How about JuliaBasics? JuliaExtras kind of sounds like a collection of leftovers, where I'd expect to find Emacs integration or something.

In any case I'm behind this idea.

**Comment by kmsquire** [comment]
To me, `JuliaBasics` suggests something more fundamental than `JuliaExtras`.  Between the two, I still like `JuliaExtras` better.

**Comment by iamed2** [comment]
I think at least DataStructures and Iterators are more fundamental than "Extras" makes them sound. Their content has moved in and out of Base and Base even had to create an Iterators submodule to include some important ones, despite an effort to move them out. But yeah, JuliaBasics isn't a great name.

I would like to find some name that indicates more about the org contents than any of these.

**Comment by tkelman** [comment]
JuliaTools
JuliaUseful
JuliaMisc
JuliaBuildingBlocks

**Comment by timholy** [comment]
JuliaContainers if you want it to be thematic rather than "extra stuff we dumped in a shoe box."

**Comment by ararslan** [comment]
I like Containers and Tools.

**Comment by tkelman** [comment]
Okay, what was formerly JuliaExtras is now JuliaContainers. Okay with everyone if I move this over in a few days? Who has done (or might need to do) recent work here who should be added?

**Comment by kmsquire** [comment]
I like `JuliaContainers` for `DataStructures` and `FunctionalCollections`.  I'm not sure `Iterators` belongs there, but go for it, and if someone has an inkling later, it can be moved to a more appropriate place.

I think the people who have commented here are the most reasonable people to add, probably followed by key Julia contributors who dabble here now and again.

**Comment by shashi** [comment]
Would love to move FunctionalCollections.jl out. I don't have the rights to do that though. I thought JuliaContainers is an org for Docker containers or something at first. Wouldn't JuliaCollections be a better name?

**Comment by tkelman** [comment]
Am I really renaming it a 4th time?

**Comment by iamed2** [comment]
Maybe wait a bit until the discussion is resolved?

**Comment by tkelman** [comment]
What's the resolution then? Renaming the org after moving the packages would require re-updating CI and URL's a second time, so would like a decision on what the final name should be before moving everything.

Thumbs up: rename JuliaContainers to JuliaCollections then move this over

Thumbs down: leave JuliaContainers called what it is then move this over

Confused: leave this package in JuliaLang (my least favorite option)

Feb 1st I'll do whichever is leading.

**Comment by quinnj** [comment]
Do note that that JuliaArrays exists as well, which might be confusing w/ JuliaCollections, but perhaps it'd make sense to merge the two anyway.

**Comment by tkelman** [comment]
JuliaArrays already has a pretty sizable number of packages in it. Due to shared Travis queues it makes sense to distribute packages across a larger number of organizations, though that does impose a bit of organizational overhead of managing members and permissions.

**Comment by shashi** [comment]
And there's a reasonable distinction between arrays and collections.

**Comment by tkelman** [comment]
Done. I'll do the metadata PR, and re-enable Travis.
