### ISSUE TITLE
Feature Request: chain(iterable_of_iterables)

### ISSUE THREAD

**Issue by krcools** [JuliaCollections/Iterators.jl#99]
I find myself often in need to iterate over all elements in an iterable collection of iterable collections. The length of the outer iterable is not known beforehand. In addition, is it possible that some of the inner collections are empty. For memory complexity reasons I do not first want to call collect on the outer collections. So this solution is not satisfactory:

```
inner_its = collect(iterable_of_iterables)
for el in chain(inner_its...)
    println(el)
end
```

Instead, I was thinking along the lines of

```
for el in unwrap(iterable_of_iterables)
    println(el)
end
```

...or whatever the most appropriate name of the iterator would be.

Since this situation is quite common, can be expressed in very general terms, and for sure is related to the use of Iterators, I was wondering whether there were any plans to include something like this in this package.

**Comment by martinholters** [comment]
Is `Base.Iterators.flatten` what you are looking for?

**Comment by krcools** [comment]
Thank you! I just discovered this 10 seconds before you post. Does not seem to be exported at the moment though... (v0.5)

**Comment by yuyichao** [comment]
You should use it as `Iterator.flatten`.
It's already documented http://docs.julialang.org/en/latest/stdlib/iterators.html#Base.Iterators.flatten

**Comment by krcools** [comment]
Thanks for pointing me there. I gave implementing it myself a shot but got stuck at the corner case of empty outer containers. Finding that in `Base` this case is not allowed either was reassuring.
